TanTan/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

from account.views import Login, signup, activate, ResetPass
from django.contrib.auth.views import (
    PasswordChangeView,
    PasswordChangeDoneView,
    # PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    LogoutView
)

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('login', Login.as_view(), name='login'),
                  path('logout', LogoutView.as_view(), name='logout'),
                  path('signup', signup, name='signup'),
                  path('order/', include('order.urls')),
                  path('activate/<slug:uidb64>/<slug:token>/', activate, name='activate'),
                  path('', include('shop.urls')),
                  path('products/', include('products.urls')),
                  path('password_change/', PasswordChangeView.as_view(), name='password_change'),
                  path('password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),

                  path('password_reset/', ResetPass.as_view(), name='password_reset'),
                  path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
                  path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),
                       name='password_reset_confirm'),
                  path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
                  path('comment/', include('comment.urls')),
                  path('profile/', include('account.urls')),
                  path('ratings/', include('star_ratings.urls', namespace='ratings')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path

from .views import add_to_cart, cart, remove_order_detail

app_name = 'order'
urlpatterns = [
    path('', add_to_cart, name='add_to_cart'),
    path('cart', cart, name='cart'),
    path('remove_order_item/<int:detail_id>', remove_order_detail, name='remove_order_item'),
]

products/urls.py
from django.urls import path
from .views import (
    ProductsListView,
    product_detail,
    Search,
    products_categories_partial,
    CategoriesListView,
)

app_name = 'products'
urlpatterns = [
    path('', ProductsListView.as_view(), name='product-list'),
    path('<int:productId>', product_detail, name='product-detail'),
    path('category/<str:category_name>', CategoriesListView.as_view(), name='product-category'),
    path('products_categories_partial', products_categories_partial, name='products_categories_partial'),
    path('search', Search.as_view(), name='search'),
]

shop/urls.py
from django.urls import path
from .views import (home,
                    HeaderPartialView,
                    FooterPartialView,
                    )

app_name = 'shop'
urlpatterns = [
    path('', home, name='home'),
    path('header/', HeaderPartialView.as_view(), name='header'),
    path('footer/', FooterPartialView.as_view(), name='footer'),
]

templates/blog/partials/footer_partial_view.html
{% load static %}

<footer id="footer"><!--Footer-->
		<div class="footer-Before">
			<div class="container">
				<div class="block-news">
					<div class="row">
						<h3>با عضویت در خبـرنامه ما از تخفیفات ویـژه ما با خبـر شوید ... </h3>
						<div class="searchform newslatter">
							<input type="text" placeholder="آدرس ایمیـل شما ..."/>
							<button type="submit" class="btn btn-default">
								<i class="fa fa-arrow-circle-o-left"></i>
							</button>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="footer-top">
			<div class="container">
				<div class="row">
					<div class="col-sm-3">
						<div class="address">
							<img src="images/home/map.png" alt="" />
						</div>
					</div>
					<div class="col-sm-3">
						<div class="address">
							<img src="images/home/map.png" alt="" />
						</div>
					</div>
					<div class="col-sm-6">
						<div class="companyinfo">
							<h2><span>SHOP</span>CENTER</h2>
							<h4>درباره ما :</h4>
							<p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده ازلورملورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد.</p>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="footer-widget">
			<div class="container">
				<div class="row">
					<div class="col-sm-3">
						<div class="single-widget">
							<h2>Service</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Online Help</a></li>
								<li><a href="#">Contact Us</a></li>
								<li><a href="#">Order Status</a></li>
								<li><a href="#">Change Location</a></li>
								<li><a href="#">FAQ’s</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="single-widget">
							<h2>Quock Shop</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">T-Shirt</a></li>
								<li><a href="#">Mens</a></li>
								<li><a href="#">Womens</a></li>
								<li><a href="#">Gift Cards</a></li>
								<li><a href="#">Shoes</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="single-widget">
							<h2>Policies</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Terms of Use</a></li>
								<li><a href="#">Privecy Policy</a></li>
								<li><a href="#">Refund Policy</a></li>
								<li><a href="#">Billing System</a></li>
								<li><a href="#">Ticket System</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3">
						<div class="single-widget">
							<h2>About Shopper</h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="#">Company Information</a></li>
								<li><a href="#">Careers</a></li>
								<li><a href="#">Store Location</a></li>
								<li><a href="#">Affillate Program</a></li>
								<li><a href="#">Copyright</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="footer-bottom" style="direction: ltr !important;">
			<div class="container">
				<div class="row">
					<p class="pull-left">Copyright © 2018
						<a target="_blank" href="http://www.1614GP.ir"><b>1614Group</b></a>. All rights reserved.
					</p>
				</div>
			</div>
		</div>

	</footer><!--/Footer-->

templates/blog/partials/header_partial_view.html
{% load static %}

<header id="header"><!--header-->
		<div class="header_top"><!--header_top-->
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<div class="contactinfo">
							<ul class="nav nav-pills">
								<li><a href="#"><i class="fa fa-phone"></i> 80 21 24 36 98+ </a></li>
								<li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="social-icons pull-right">
							<ul class="nav navbar-nav">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
								<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
								<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header_top-->

		<div class="header-middle"><!--header-middle-->
			<div class="container">
				<div class="row">
					<!-- <div class="col-sm-4 header-middle-menu">
						<div class="shop-menu pull-left">
							<ul class="nav navbar-nav">
								<li><a href="checkout.html"><i class="fa fa-crosshairs"></i> پرداخت</a></li>
							</ul>
						</div>
					</div> -->

					<div class="col-sm-4" style="text-align: left;">
						<div class="logo">
							<a href="index.html"><img src="images/home/logo.png" alt="Logo" style="text-align: center;" /></a>
						</div>
					</div>

					<div class="col-sm-8 header-middle-menu">
						<div class="shop-menu pull-right">
							<ul class="nav navbar-nav">
								<li><a href="#"><i class="fa fa-user"></i> حساب کاربـری</a></li>
								<li><a href="#"><i class="fa fa-star"></i> لیست علاقه مندی ها</a></li>
								<li><a href="{% url 'login' %}"><i class="fa fa-lock"></i> ورود</a></li>
								<li><a href=" {% url 'order:cart' %}"><i class="fa fa-shopping-cart"></i> سبد خریـد</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-middle-->

		<div class="header-bottom"><!--header-bottom-->
			<div class="container">
				<div class="row">

					<div class="col-sm-3">
						<div class="search_box pull-left">
                            {% include 'blog/partials/search_component.html' %}
						</div>
					</div>

					<div class="col-sm-9">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
						<div class="mainmenu pull-right">
							<ul class="nav navbar-nav collapse navbar-collapse">
								<li><a href="{% url 'shop:home' %}" class="active">خـانه</a></li>
								<li class="dropdown"><a href="#">فروشگـاه<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><a href="{% url 'products:product-list' %}">محصولات</a></li>
										<li><a href="product-details.html">جزئیات محصولات</a></li>
										<li><a href="checkout.html">پرداخت</a></li>
										<li><a href="{% url 'order:cart' %}">سبـد خریـد</a></li>
										<li><a href="{% url 'login' %}">ورود</a></li>
                                    </ul>
                                </li>
								<li><a href="About.html">درباره مـا</a></li>
								<li><a href="contact-us.html">تماس با مـا</a></li>
							</ul>
						</div>
					</div>

				</div>
			</div>
		</div><!--/header-bottom-->
	</header><!--/header-->

templates/blog/partials/products_categories_partial.html
<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>دسته بندی محصولات</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->

							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="#">همه</a></h4>
								</div>
							</div>
                            {% for category in categories %}
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="{% url 'products:product-category' category.slug %}">{{ category.title }}</a></h4>
								</div>
							</div>
                            {% endfor %}
						</div><!--/category-productsr-->

						<div class="brands_products"><!--brands_products-->
							<h2>برنـد ها</h2>
							<div class="brands-name">
								<ul class="nav nav-pills nav-stacked">
									<li><a href=""> <span class="pull-left">(50)</span>برنـد 1</a></li>
									<li><a href=""> <span class="pull-left">(56)</span>برنـد 2</a></li>
									<li><a href=""> <span class="pull-left">(27)</span>برنـد 3</a></li>
									<li><a href=""> <span class="pull-left">(32)</span>برنـد 4</a></li>
									<li><a href=""> <span class="pull-left">(5)</span>برنـد 5</a></li>
								</ul>
							</div>
						</div><!--/brands_products-->

						<div class="price-range"><!--price-range-->
							<h2>فیلتـر قیمـت</h2>
							<div class="well">
								 <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="1000000" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
								 <b>1.000.000 ريال</b> <b class="pull-left">0 ريال</b>
							</div>
						</div><!--/price-range-->

						<div class="shipping text-center"><!--shipping-->
							<img src="images/home/shipping.jpg" alt="" />
						</div><!--/shipping-->
                    </div>
</div>

templates/blog/partials/products_component_partial.html
{#<div class="product-image-wrapper">#}
{#    <div class="single-products">#}
{#        <div class="productinfo text-center">#}
{#            <img height="250rem" src="{{ product.image.url }}" alt="" />#}
{#            <h2>{{ product.price }} ريال</h2>#}
{#            <p>{{ product.description }}</p>#}
{#            <a href="{% url 'order:add_to_cart' %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>افزودن به سبـد خریـد</a>#}
{#        </div>#}
{#        <div class="product-overlay">#}
{#            <div class="overlay-content">#}
{#                <h2>{{ product.price }} ريال</h2>#}
{#                <p>{{ product.description }}</p>#}
{#                <form method="post" action="{% url 'order:cart' %}">#}
{#                    {% csrf_token %}#}
{#                    {{ cart.product_id }}#}
{#                    <label>تعداد :</label>#}
{#                    {{ cart.amount }}#}
{#                    <button type="submit" class="btn btn-default cart">#}
{#                        <i class="fa fa-shopping-cart"></i>#}
{#                        افـزودن به سبـد خریـد#}
{#                    </button>#}
{#                </form>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#    <div class="choose">#}
{#        <ul class="nav nav-pills nav-justified">#}
{#            <li><a href=""><i class="fa fa-plus-square"></i>لیست علاقه مندی ها</a></li>#}
{#            <li><a href="{{ product.get_absolute_url }}"><i class="fa fa-plus-square"></i>مشاهده</a></li>#}
{#        </ul>#}
{#    </div>#}
{#</div>#}

{% load ratings %}


<div class="card top-product-card">
    <div class="card-body"><span class="badge badge-success">Sale</span><a class="wishlist-btn" href="#"><i class="lni lni-heart"></i></a><a class="product-thumbnail d-block" href="{% url 'products:product-detail' product.id %}"><img class="mb-2" src="{{  product.image.url }}" alt="{{ product.title }}" style="height: 11rem;"></a><a class="product-title d-block" href="{% url 'products:product-detail' product.id %}">{{ product.title }}</a>
        <p class="sale-price">{{ product.price }} تومان<span></span></p>
        <div class="product-rating">{% ratings product %}</div><a class="btn btn-success btn-sm" href="{{ product.get_absolute_url }}"><i class="lni lni-eye"></i></a>
    </div>
</div>

templates/blog/partials/search_component.html
<form action="{% url 'products:search' %}">
    <input type="search" name="q" placeholder="جستجو" value="{{ request.GET.q }}">
</form>