TanTan/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

from account.views import Login, signup, activate, ResetPass
from django.contrib.auth.views import (
    PasswordChangeView,
    PasswordChangeDoneView,
    # PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    LogoutView
)

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('login', Login.as_view(), name='login'),
                  path('logout', LogoutView.as_view(), name='logout'),
                  path('signup', signup, name='signup'),
                  path('order/', include('order.urls')),
                  path('activate/<slug:uidb64>/<slug:token>/', activate, name='activate'),
                  path('', include('shop.urls')),
                  path('products/', include('products.urls')),
                  path('password_change/', PasswordChangeView.as_view(), name='password_change'),
                  path('password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),

                  path('password_reset/', ResetPass.as_view(), name='password_reset'),
                  path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
                  path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(),
                       name='password_reset_confirm'),
                  path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
                  path('comment/', include('comment.urls')),
                  path('profile/', include('account.urls')),
                  path('ratings/', include('star_ratings.urls', namespace='ratings')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from .views import profile, edit_profile

app_name = 'account'
urlpatterns = [
    path('', profile, name='profile'),
    path('edit/', edit_profile, name='edit_profile'),
]

order/urls.py
from django.urls import path

from .views import add_to_cart, cart, remove_order_detail

app_name = 'order'
urlpatterns = [
    path('', add_to_cart, name='add_to_cart'),
    path('cart', cart, name='cart'),
    path('remove_order_item/<int:detail_id>', remove_order_detail, name='remove_order_item'),
]

products/urls.py
from django.urls import path
from .views import (
    ProductsListView,
    product_detail,
    Search,
    products_categories_partial,
    CategoriesListView,
)

app_name = 'products'
urlpatterns = [
    path('', ProductsListView.as_view(), name='product-list'),
    path('<int:productId>', product_detail, name='product-detail'),
    path('category/<str:category_name>', CategoriesListView.as_view(), name='product-category'),
    path('products_categories_partial', products_categories_partial, name='products_categories_partial'),
    path('search', Search.as_view(), name='search'),
]

shop/urls.py
from django.urls import path
from .views import (home,
                    HeaderPartialView,
                    FooterPartialView,
                    )

app_name = 'shop'
urlpatterns = [
    path('', home, name='home'),
    path('header/', HeaderPartialView.as_view(), name='header'),
    path('footer/', FooterPartialView.as_view(), name='footer'),
]

templates/blog/base.html
{% load static %}
{% load render_partial %}
{% load gravatar %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, viewport-fit=cover, shrink-to-fit=no">
    <meta name="description" content="Suha - Multipurpose Ecommerce Mobile HTML Template">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="theme-color" content="#100DD1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <!-- The above tags *must* come first in the head, any other head content must come *after* these tags-->
    <!-- Title-->
    <title>Suha - Multipurpose Ecommerce Mobile HTML Template</title>
    <!-- Favicon-->
    <link rel="icon" href="{% static 'img/icons/icon-72x72.png' %}">
    <!-- Apple Touch Icon-->
    <link rel="apple-touch-icon" href="{% static 'img/icons/icon-96x96.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'img/icons/icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="167x167" href="{% static 'img/icons/icon-167x167.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/icons/icon-180x180.png' %}">
    <!-- Stylesheet-->
    <link rel="stylesheet" href="{% static 'style-rtl.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!-- star ratings -->
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
    <!-- Web App Manifest-->
    <link rel="manifest" href="{% static 'manifest.json' %}">
  </head>
  <body>
    <!-- Preloader-->
    <div class="preloader" id="preloader">
      <div class="spinner-grow text-secondary" role="status">
        <div class="sr-only">بارگذاری...</div>
      </div>
    </div>
    <!-- Header Area-->
    <div class="header-area" id="headerArea">
      <div class="container h-100 d-flex align-items-center justify-content-between">
        <!-- Logo Wrapper-->
        <div class="logo-wrapper"><a href="{% url 'shop:home' %}"><img src="{% static 'img/tantan-logo.jpg' %}" alt="" height="35rem" width="35rem" style="border-radius: 50%;"></a></div>
        <!-- Search Form-->
        <div class="top-search-form">
          <form action="{% url 'products:search' %}" method="get">
            <input class="form-control" type="search" placeholder="جستجوی محصول" value="{{ request.GET.q }}" name="q">
            <button type="submit"><i class="fa fa-search"></i></button>
          </form>
        </div>
        <!-- Navbar Toggler-->
        <div class="suha-navbar-toggler d-flex flex-wrap" id="suhaNavbarToggler"><span></span><span></span><span></span></div>
      </div>
    </div>
    <!-- Sidenav Black Overlay-->
    <div class="sidenav-black-overlay"></div>
    <!-- Side Nav Wrapper-->
    <div class="suha-sidenav-wrapper" id="sidenavWrapper">
      <!-- Sidenav Profile-->
      <div class="sidenav-profile">
        <div class="user-profile"><img src="{% gravatar_url user.email 150 %}" alt=""></div>
        <div class="user-info">
          <h6 class="user-name mb-0">{{ user.username }}</h6>
        </div>
      </div>
      <!-- Sidenav Nav-->
      <ul class="sidenav-nav pl-0">
        <li><a href="{% url 'account:profile' %}"><i class="lni lni-user"></i>پروفایل من</a></li>
        <li class="suha-dropdown-menu"><a href="wishlist-grid.html"><i class="lni lni-heart"></i>لیست علاقه مندی</a>
          <ul>
            <li><a href="wishlist-grid.html">- شبکه ای</a></li>
            <li><a href="wishlist-list.html">- لیستی</a></li>
          </ul>
        </li>
        <li><a href="{% url 'logout' %}"><i class="lni lni-power-switch"></i>خروج</a></li>
      </ul>
      <!-- Go Back Button-->
      <div class="go-home-btn" id="goHomeBtn"><i class="lni lni-arrow-left"></i></div>
    </div>
{#    <!-- PWA Install Alert-->#}
{#    <div class="toast pwa-install-alert shadow" id="pwaInstallToast" role="alert" aria-live="assertive" aria-atomic="true" data-delay="8000" data-autohide="true">#}
{#      <div class="toast-body">#}
{#        <button class="ml-3 close" type="button" data-dismiss="toast" aria-label="Close"><span aria-hidden="true">&times;</span></button>#}
{#        <div class="content d-flex align-items-center mb-2"><img src="img/icons/icon-72x72.png" alt="">#}
{#          <h6 class="mb-0 text-white">افزودن به صفحه اصلی</h6>#}
{#        </div><span class="mb-0 d-block text-white">سوهارا در صفحه اصلی تلفن همراه خود اضافه کنید. بر روی<strong class="mx-1">"افزودن به صفحه اصلی"</strong>کلیک کنید</span>#}
{#      </div>#}
{#    </div>#}
    {% block content %}

    {% endblock %}
    <!-- Footer Nav-->
    <div class="footer-nav-area" id="footerNav">
      <div class="container h-100 px-0">
        <div class="suha-footer-nav h-100">
          <ul class="h-100 d-flex align-items-center justify-content-between pl-0">
            <li class="active"><a href="{% url 'shop:home' %}"><i class="lni lni-home"></i>خانه</a></li>
            <li><a href="{% url 'order:cart' %}"><i class="lni lni-shopping-basket"></i>سبد خرید</a></li>
            <li><a href="{% url 'account:profile' %}"><i class="lni lni-user"></i>پروفایل</a></li>
          </ul>
        </div>
      </div>
    </div>
    <!-- All JavaScript Files-->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.easing.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
    <script src="{% static 'js/default/jquery.passwordstrength.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/jarallax.min.js' %}"></script>
    <script src="{% static 'js/jarallax-video.min.js' %}"></script>
    <script src="{% static 'js/default/dark-mode-switch.js' %}"></script>
    <script src="{% static 'js/default/no-internet.js' %}"></script>
    <script src="{% static 'js/default/active.js' %}"></script>
    <script src="{% static 'js/pwa.js' %}"></script>
    <!-- star ratings js -->
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
  </body>
</html>

templates/blog/cart.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}

{#    <section id="cart_items">#}
{#		<div class="container">#}
{#			<div class="breadcrumbs">#}
{#				<ol class="breadcrumb">#}
{#				  <li><a href="/">خانـه</a></li>#}
{#				  <li class="active">سبد خرید</li>#}
{#				</ol>#}
{#			</div><!--/breadcrums-->#}
{##}
{#			{% if order != None and order_detail|length > 0 %}#}
{#                <div class="table-responsive cart_info">#}
{#                    <table class="table table-condensed">#}
{#					<thead>#}
{#						<tr class="cart_menu">#}
{#							<td class="image">کـالا</td>#}
{#							<td class="description"></td>#}
{#							<td class="price">قیمت</td>#}
{#							<td class="quantity">تعـداد</td>#}
{#							<td class="total">مجمـوع</td>#}
{#							<td></td>#}
{#						</tr>#}
{#					</thead>#}
{#					<tbody>#}
{#						{% for item in order_detail %}#}
{#                            <tr>#}
{#							<td class="cart_product">#}
{#								<a href=""><img src="{{ item.product.image.url }}" alt="{{ item.product.title }}" height="50rem" width="50rem"></a>#}
{#							</td>#}
{#							<td class="cart_description">#}
{#								<h4><a href="">{{ item.product.title }}</a></h4>#}
{#							</td>#}
{#							<td class="cart_price">#}
{#								<p>{{ item.unit_price }} ريال</p>#}
{#							</td>#}
{#							<td class="cart_quantity">#}
{#								<div class="cart_quantity_button">#}
{#									<a class="cart_quantity_up" href=""> + </a>#}
{#									<input class="cart_quantity_input" type="text" name="quantity" value="{{ item.amount }}" autocomplete="off" size="2">#}
{#									<a class="cart_quantity_down" href=""> - </a>#}
{#								</div>#}
{#							</td>#}
{#							<td class="cart_total">#}
{#								<p class="cart_total_price">{{ item.get_detail_total_price }} ريال</p>#}
{#							</td>#}
{#							<td class="cart_delete">#}
{#								<a class="cart_quantity_delete" href=""><i class="fa fa-times"></i></a>#}
{#							</td>#}
{#						</tr>#}
{#                        {% endfor %}#}
{#					</tbody>#}
{#				</table>#}
{#                </div>#}
{#            {% else %}#}
{#                <div class="alert alert-warning">#}
{#                    <p>هیچ محصولی در سبد خرید شما یافت نشد</p>#}
{#                </div>#}
{#            {% endif %}#}
{##}
{#		</div>#}
{#	</section>#}
{##}
{#    <section id="do_action" style="margin-top: 3rem;">#}
{#		<div class="container">#}
{#			<div class="heading">#}
{#				<h3>نهایی کردن سفارش یا ادامه خریـد ؟! </h3>#}
{#				<p>در صورتیکـه کوپن خریـد و یا کد تخفیف داریـد میتوانید از آن استفاده نمایید | با استفاده از بخش مربوطه هزینه حمل و نقل خود را محاسبـه نمایید</p>#}
{#			</div>#}
{#			<div class="row">#}
{#				<div class="col-sm-6">#}
{#					<div class="chose_area">#}
{#						<ul class="user_option">#}
{#							<li>#}
{#								<h3>استفاده از کوپـن خریـد / کارت تخفیـف :</h3>#}
{#							</li>#}
{#							<li class="single_field zip-field">#}
{#								<input type="text" placeholder="کد تخفیف خود را وارد نمایید ...">#}
{#							</li>#}
{#							<li>#}
{#								<a class="btn btn-default update" href="">بررسی و اعمال</a>#}
{#							</li>#}
{#						</ul>#}
{#						<ul class="user_info">#}
{#							<h3>محاسبـه هزینـه حمل و نقل</h3>#}
{#							<li class="single_field">#}
{#								<label>استان :</label>#}
{#								<select>#}
{#									<option>تهـران</option>#}
{#									<option>اصفهان</option>#}
{#									<option>آذربایجان غربـی</option>#}
{#									<option>آذربایجان شرقـی</option>#}
{#								</select>#}
{##}
{#							</li>#}
{#							<li class="single_field">#}
{#								<label>شهر / منطقه</label>#}
{#								<select>#}
{#									<option>تهران</option>#}
{#									<option>اصفهان</option>#}
{#									<option>خـوی</option>#}
{#									<option>تبریـز</option>#}
{#								</select>#}
{##}
{#							</li>#}
{#							<li class="single_field zip-field">#}
{#								<label>کد پستی :</label>#}
{#								<input type="text">#}
{#							</li>#}
{#						</ul>#}
{#						<a class="btn btn-default update" href="">محاسبـه هزینـه حمل و نقـل</a>#}
{#					</div>#}
{#				</div>#}
{#				<div class="col-sm-6">#}
{#					<div class="total_area">#}
{#						<ul>#}
{#							<li>مجمـوع سبـد خریـد <span>2.030.000 ريال</span></li>#}
{#							<li>مالیـات (9%) <span>182.700 ريال</span></li>#}
{#							<li>هزینـه حمل و نقـل <span>رایـگان</span></li>#}
{#							<li>مجمـوع <span>2.212.700 ريال</span></li>#}
{#						</ul>#}
{#							<a class="btn btn-default update" href="shop.html">به روز رسانی سبـد خریـد </a>#}
{#							<a class="btn btn-default check_out" href="checkout.html">پرداخت</a>#}
{#					</div>#}
{#				</div>#}
{#			</div>#}
{#		</div>#}
{#	</section>#}






        <div class="page-content-wrapper">
      <div class="container">
        <!-- Cart Wrapper-->
        <div class="cart-wrapper-area py-3">
          <div class="cart-table card mb-3">
            <div class="table-responsive card-body">
              <table class="table mb-0">
                <tbody>
                    {% if order_detail %}
                        {% for item in order_detail %}
                          <tr>
                            <th scope="row"><a class="remove-product" href="{% url 'order:remove_order_item' item.id %}"><i class="lni lni-close"></i></a></th>
                            <td><img src="{{ item.product.image.url }}" alt="{{ item.product.title }}"></td>
                            <td><a href="single-product.html">{{ item.product.title }}<span>ت {{ item.unit_price }} × {{ item.amount }}</span></a></td>
                            <td>
                              <div class="quantity">
                                <input class="qty-text" type="text" value="{{ item.amount }}">
                              </div>
                            </td>
                          </tr>
                        {% endfor %}
                    {% else %}
                        <p>در حال حاضر هیچ محصولی در سبد خرید شما وجود ندارد</p>
                    {% endif %}
                </tbody>
              </table>
            </div>
          </div>
          <!-- Coupon Area-->
          <div class="card coupon-card mb-3">
            <div class="card-body">
              <div class="apply-coupon">
                <h6 class="mb-0">کد تخفیف دارید؟</h6>
                <p class="mb-2">برای تخفیف کد خود را وارد کنید</p>
                <div class="coupon-form">
                  <form action="#">
                    <input class="form-control" type="text" placeholder="SUHA30">
                    <button class="btn btn-primary" type="submit">اعمال</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
          <!-- Cart Amount Area-->
          <div class="card cart-amount-area">
            <div class="card-body d-flex align-items-center justify-content-between">
              <h5 class="total-price mb-0"><span class="counter">{{ order.get_total_price }}</span> تومان </h5><a class="btn btn-warning" href="checkout.html">تسویه حساب</a>
            </div>
          </div>
        </div>
      </div>
    </div>



{% endblock %}

templates/blog/categories.html
{% extends 'blog/base.html' %}
{% load static %}
{% load render_partial %}



{% block content %}

        <div class="page-content-wrapper">
        {% if category.image %}
            <!-- Catagory Single Image-->
            <div class="catagory-single-img" style="background-image: url({{  category.image.url }}); background-position: center center; background-size: contain; background-repeat: no-repeat;"></div>
        {% endif %}
      <!-- Product Catagories-->
      {% if sub_category %}
          <div class="product-catagories-wrapper py-3">
        <div class="container">
          <div class="section-heading">
            <h6 class="ml-1">دسته بندی های این دسته</h6>
          </div>
          <div class="product-catagory-wrap">
            <div class="row g-3">
              {% for sub_cat in sub_category %}
                  <!-- Single Catagory Card-->
                  <div class="col-4">
                    <div class="card catagory-card">
                      <div class="card-body"><a href="{% url 'products:product-category' sub_cat.slug %}"><i class="lni lni-heart"></i><span>{{ sub_cat.title }}</span></a></div>
                    </div>
                  </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
      {% endif %}
        {% if object_list %}
            <!-- Top Products-->
            <div class="top-products-area pb-3">
                <div class="container">
                  <div class="section-heading d-flex align-items-center justify-content-between">
                    <h6 class="ml-1 mt-2">محصولات دسته بندی: {{ category.title }}</h6>
                  </div>
                  <div class="row g-3">
        {#            <!-- Single Top Product Card-->#}
        {#            <div class="col-6 col-md-4 col-lg-3">#}
        {#              <div class="card top-product-card">#}
        {#                <div class="card-body"><span class="badge badge-success">Sale</span><a class="wishlist-btn" href="#"><i class="lni lni-heart"></i></a><a class="product-thumbnail d-block" href="single-product.html"><img class="mb-2" src="img/product/11.png" alt=""></a><a class="product-title d-block" href="single-product.html">Beach Cap</a>#}
        {#                  <p class="sale-price">$13<span>$42</span></p>#}
        {#                  <div class="product-rating"><i class="lni lni-star-filled"></i><i class="lni lni-star-filled"></i><i class="lni lni-star-filled"></i><i class="lni lni-star-filled"></i><i class="lni lni-star-filled"></i></div><a class="btn btn-success btn-sm add2cart-notify" href="#"><i class="lni lni-plus"></i></a>#}
        {#                </div>#}
        {#              </div>#}
        {#            </div>#}

                      {% for product in object_list %}
                          <!-- Single Catagory Card-->
                          <div class="col-6 col-md-4 col-lg-3">
                              {% include 'blog/partials/products_component_partial.html' with product=product %}
                          </div>
                      {% endfor %}
                  </div>
                </div>
              </div>
        {% else %}
            <div class="top-products-area pb-3">
                <div class="container">
                  <div class="section-heading d-flex align-items-center justify-content-center">
                    <h6 class="ml-1 mt-5">هیچ محصولی در این دسته بندی موجود نیست.</h6>
                  </div>
                </div>
              </div>
        {% endif %}
    </div>

{% endblock %}

templates/blog/product-list.html
{% extends 'blog/base.html' %}
{% load static %}
{% load render_partial %}


{% block content %}
	<section>
		<div class="container">
			<div class="row">

				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
                        {% for product in object_list %}
						<div class="col-sm-4 pull-right">
							{% include 'blog/partials/products_component_partial.html' with product=product %}
						</div>
                        {% endfor %}

                        <div class="clearfix"></div>

                    {% if is_paginated %}
						<ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li><a href="?page={{ page_obj.previous_page_number }}"><i class="fas fa-arrow-circle-right" style="font-family: FontAwesome"></i></a></li>
                        {% endif %}
                        {% for page in paginator.page_range %}
                            {% if page == page_obj.number %}
							    <li class="active"><a href="?page={{ page }}">{{ page }}</a></li>
                            {% else %}
                                <li><a href="?page={{ page }}">{{ page }}</a></li>
                            {% endif %}
                        {% endfor %}
						{% if page_obj.has_next %}
                            <li><a href="?page={{ page_obj.next_page_number }}"><i class="fas fa-arrow-circle-left" style="font-family: FontAwesome"></i></a></li>
                        {% endif %}
						</ul>
                    {% endif %}

					</div><!--features_items-->
				</div>

                {% render_partial 'products:products_categories_partial' %}

			</div>
		</div>
	</section>
{% endblock %}

templates/blog/shop-list.html
{% extends 'blog/base.html' %}
{% load static %}
{% load render_partial %}


{% block content %}
{#	<section>#}
{#		<div class="container">#}
{#			<div class="row">#}
{##}
{#				<div class="col-sm-9 padding-right">#}
{#					<div class="features_items"><!--features_items-->#}
{#                        {% for product in products %}#}
{#						<div class="col-sm-4 pull-right">#}
{#							{% include 'blog/partials/products_component_partial.html' with product=product %}#}
{#						</div>#}
{#                        {% endfor %}#}
{##}
{#                        <div class="clearfix"></div>#}
{##}
{#                    {% if is_paginated %}#}
{#						<ul class="pagination">#}
{#                        {% if page_obj.has_previous %}#}
{#                            <li><a href="?page={{ page_obj.previous_page_number }}"><i class="fas fa-arrow-circle-right" style="font-family: FontAwesome"></i></a></li>#}
{#                        {% endif %}#}
{#                        {% for page in paginator.page_range %}#}
{#                            {% if page == page_obj.number %}#}
{#							    <li class="active"><a href="?page={{ page }}">{{ page }}</a></li>#}
{#                            {% else %}#}
{#                                <li><a href="?page={{ page }}">{{ page }}</a></li>#}
{#                            {% endif %}#}
{#                        {% endfor %}#}
{#						{% if page_obj.has_next %}#}
{#                            <li><a href="?page={{ page_obj.next_page_number }}"><i class="fas fa-arrow-circle-left" style="font-family: FontAwesome"></i></a></li>#}
{#                        {% endif %}#}
{#						</ul>#}
{#                    {% endif %}#}
{##}
{#					</div><!--features_items-->#}
{#				</div>#}
{##}
{#                {% render_partial 'products:products_categories_partial' %}#}
{##}
{#			</div>#}
{#		</div>#}
{#	</section>#}







<div class="page-content-wrapper">
      <!-- Top Products-->
      <div class="top-products-area py-3">
        <div class="container">
          <div class="section-heading d-flex align-items-center justify-content-between">
            <h6 class="ml-1">All Products</h6>
            <!-- Layout Options-->
            <div class="layout-options"><a href="shop-grid.html"><i class="lni lni-grid-alt"></i></a><a class="active" href="shop-list.html"><i class="lni lni-radio-button"></i></a></div>
          </div>
          <div class="row g-3">
            {% for product in products %}
                <!-- Single Weekly Product Card-->
                <div class="col-12 col-md-6">
                  <div class="card weekly-product-card">
                    <div class="card-body d-flex align-items-center">
                      <div class="product-thumbnail-side"><span class="badge badge-success">Sale</span><a class="wishlist-btn" href="#"><i class="lni lni-heart"></i></a><a class="product-thumbnail d-block" href="single-product.html"><img src="{{  product.image.url }}" alt="{{ product.title }}"></a></div>
                      <div class="product-description"><a class="product-title d-block" href="{% url 'products:product-detail' product.id %}">{{ product.title }}</a>
                        <p class="sale-price"> تومان{{ product.price }}</p>
                        <div class="product-rating"><i class="lni lni-star-filled"></i>4.88 (39)</div><a class="btn btn-success btn-sm add2cart-notify" href="{% url 'products:product-detail' product.id %}"><i class="mr-1 lni lni-eye"></i>نمایش محصول</a>
                      </div>
                    </div>
                  </div>
                </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>



{% endblock %}